
import { FaTruckMedical, FaHandHoldingMedical } from "react-icons/fa6";
import { GiLifeSupport, GiHealing } from "react-icons/gi";

export const REASONS = [
    {
      title: "Certified Professionals",
      description:
        "All our caregivers are licensed, certified, and thoroughly background-checked to ensure safe and reliable care.",
    },
    {
      title: "Personalized Care Plans",
      description: "Each service is tailored to your specific health needs, goals, and lifestyle preferences.",
    },
    {
      title: "Flexible Scheduling",
      description:
        "Our services are available 24/7 to accommodate your schedule and changing care needs.",
    },
    {
      title: "Professional Support",
      description: "We provide ongoing supervision, continuous training, and strict quality assurance across all services.",
    },
    {
      title: "Compassionate Care",
      description:
        "We treat every client with dignity, respect, and genuine compassion at all times.",
    },
    {
      title: "Affordable Options",
      description: "We work closely with you to find care solutions that fit your budget without compromising quality.",
    },
] as const;

export const SERVICES = [
    {
        icon: FaHandHoldingMedical,
        title: "Support Community Connection Services",
        subtitle: "Our goal is to empower clients to stay socially active, connected, and confident, enriching their lives through community involvement.",
        description: "We help clients build meaningful connections and integrate seamlessly into their local communities. Our community support services are designed to enhance social engagement, foster relationships, and promote overall well-being.",

        details: [
            // "Community group introductions and participation",
            // "Social engagement program coordination",
            // "Peer support network establishment",
            // "Local resource and activity matching",
            // "Community event planning and attendance",
            "Social skill development and confidence building",
            "Volunteering with local non-profit organizations",
            "Touring museums and nature centers",
            "Making small purchases to promote money management skills",
            "Touring local businesses to learn about potential work opportunities",
            "Participating in recreation to promote an active, healthy lifestyle and much more!"
        ],
        image: "/assets/community.jpg",
    },
    {
        icon: GiLifeSupport, 
        title: "Residential Services & Support",
        subtitle: "Our team works closely with clients and their families to ensure consistent, professional, and compassionate care every day.",
        description: "We provide comprehensive medical and daily living support in residential settings, ensuring clients receive the care they need in the comfort and safety of their homes. Our residential services are tailored to promote health, independence, and overall well-being.",
        details: [
            "Medication management and administration support",
            "Chronic disease management assistance in home environment",
            "Post-hospitalization residential care coordination",
            "Medical equipment setup and maintenance support",
            "Vital signs monitoring and health status tracking",
            "Care plan implementation and progress documentation",
        ],
        image: "/assets/resipite.png",
    },
    {
        icon: GiHealing,
        title: "Respite Services",
        subtitle: "Our flexible respite solutions help maintain continuity of care while supporting the well-being of primary caregivers and their loved ones.",
        description: "We provide temporary relief and support for primary caregivers, allowing them to rest, recharge, and attend to other responsibilities. Our respite services ensure that both caregivers and clients receive the care and support they need without interruption",
        details: [
            "Short-term caregiving relief",
            "Temporary in-home support services",
            "Caregiver rest and rejuvenation periods",
            "Emergency backup care arrangements",
            "Temporary companionship services",
            "Flexible scheduling for caregiver breaks",
        ],
        image: "/assets/assisted-living.png",
    },
    // {
    //     icon: GiLifeSupport, 
    //     title: "SCC Day Program",
    //     subtitle: "Empower clients to stay socially active, connected, and confident, enriching their lives through community involvement.",
    //     description: "Clients build meaningful connections and integrate seamlessly into their local communities. Our community support services are designed to enhance social engagement, foster relationships, and promote overall well-being.",
    //     details: [
    //         "Volunteering with local non-profit organizations",
    //         "Touring museums and nature centers",
    //         "Making small purchases to promote money management skills",
    //         "Touring local businesses to learn about potential work opportunities",
    //         "Participating in recreation to promote an active, healthy lifestyle and much more!",
    //     ],
    //     image: "/assets/care-1.jpg",
    // },
    {
        icon: FaTruckMedical,
        title: "Non-Medical Transport",
        subtitle: "Our caregivers ensure timely, courteous, and supportive transportation so clients can move confidently through their daily routines and community activities.",
        description: "We provide reliable and safe transportation assistance to help clients attend appointments, run errands, and stay socially active. Our non-medical transport services are designed to promote independence, convenience, and peace of mind.",
        details: [
            "Medical appointment transportation",
            "Grocery shopping and errand assistance",
            "Social event and activity transportation",
            "Pharmacy and prescription pickup",
            "Family visit coordination and transport",
            "Safe and comfortable vehicle access",
        ],
        image: "/assets/transport.png",
    },
] as const;

export const Former_SERVICES = [
    {
        title: "Skilled Nursing",
        description: "Professional nursing services provided by licensed registered nurses.",
        details: [
            "Wound care and dressing changes",
            "Medication management and administration",
            "Post-operative care and monitoring",
            "Catheter care and management",
            "Health monitoring and vital signs assessment",
            "Patient education and health coaching",
        ],
        image: "/nurse-patient-care-medical-equipment.jpg",
    },
    {
        title: "Physical Therapy",
        description: "Personalized rehabilitation programs to improve mobility and strength.",
        details: [
            "Mobility and balance training",
            "Strength and conditioning exercises",
            "Pain management and rehabilitation",
            "Fall prevention strategies",
            "Post-injury and post-surgical recovery",
            "Chronic condition management",
        ],
        image: "/physical-therapy-elderly-patient-exercise.jpg",
    },
    {
        title: "Home Health Aides",
        description: "Compassionate assistance with daily living activities.",
        details: [
            "Bathing and personal hygiene assistance",
            "Dressing and grooming support",
            "Meal preparation and feeding assistance",
            "Light housekeeping and laundry",
            "Mobility assistance and transfers",
            "Companionship and emotional support",
        ],
        image: "/caregiver-assisting-elderly-person-activity.jpg",
    },
    {
        title: "Personal Care Services",
        description: "Support with personal hygiene and daily care needs.",
        details: [
            "Assistance with activities of daily living",
            "Personal hygiene support",
            "Grooming and appearance care",
            "Toileting assistance",
            "Incontinence management",
            "Skin care and pressure ulcer prevention",
        ],
        image: "/senior-person-self-care-activities.jpg",
    },
    {
        title: "Companionship Services",
        description: "Meaningful social interaction and emotional support.",
        details: [
            "Social companionship and conversation",
            "Emotional support and listening",
            "Activity engagement and entertainment",
            "Community outings and errands",
            "Medication reminders and appointment support",
            "Advocacy and communication with family",
        ],
        image: "/elderly-pair-happy-social-connection.jpg",
    },
    {
        title: "Specialized Care Programs",
        description: "Customized care for specific medical conditions.",
        details: [
            "Diabetes management support",
            "Heart disease and hypertension care",
            "Alzheimer's and dementia support",
            "Parkinson's disease care",
            "Post-stroke recovery programs",
            "Chronic pain management",
        ],
        image: "/healthcare-professional-medical-consultation.jpg",
    },
] as const;

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" }
] as const;

export const US_TERRITORIES = [
  { value: "AS", label: "American Samoa" },
  { value: "GU", label: "Guam" },
  { value: "MP", label: "Northern Mariana Islands" },
  { value: "PR", label: "Puerto Rico" },
  { value: "VI", label: "U.S. Virgin Islands" }
] as const;

export const ALL_US_REGIONS = [...US_STATES, ...US_TERRITORIES] as const;

export const COUNTRIES = [
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "MX", label: "Mexico" },
  { value: "GB", label: "United Kingdom" },
  { value: "AU", label: "Australia" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "IT", label: "Italy" },
  { value: "ES", label: "Spain" },
  { value: "JP", label: "Japan" },
  { value: "CN", label: "China" },
  { value: "IN", label: "India" },
  { value: "BR", label: "Brazil" },
  { value: "RU", label: "Russia" },
  { value: "KR", label: "South Korea" },
  { value: "NL", label: "Netherlands" },
  { value: "CH", label: "Switzerland" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "DK", label: "Denmark" },
  { value: "FI", label: "Finland" },
  { value: "AT", label: "Austria" },
  { value: "BE", label: "Belgium" },
  { value: "PT", label: "Portugal" },
  { value: "IE", label: "Ireland" },
  { value: "PL", label: "Poland" },
  { value: "CZ", label: "Czech Republic" },
  { value: "HU", label: "Hungary" },
  { value: "GR", label: "Greece" },
  { value: "TR", label: "Turkey" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "ZA", label: "South Africa" },
  { value: "AR", label: "Argentina" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colombia" },
  { value: "PE", label: "Peru" },
  { value: "NZ", label: "New Zealand" },
  { value: "SG", label: "Singapore" },
  { value: "MY", label: "Malaysia" },
  { value: "TH", label: "Thailand" },
  { value: "ID", label: "Indonesia" },
  { value: "PH", label: "Philippines" },
  { value: "VN", label: "Vietnam" },
  { value: "EG", label: "Egypt" },
  { value: "NG", label: "Nigeria" },
  { value: "KE", label: "Kenya" },
  { value: "IL", label: "Israel" }
] as const;


export const ALL_COUNTRIES = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazil" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CR", label: "Costa Rica" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "GD", label: "Grenada" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "North Korea" },
  { value: "KR", label: "South Korea" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Laos" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "MK", label: "North Macedonia" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syria" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatican City" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" }
] as const;